### ISSUE TITLE
Wingpanel crashes when fetching media when io.elementary.music is not present

### ISSUE THREAD

**Issue by SweetHangerine** [elementary/wingpanel-indicator-sound#107]
As the title states, Wingpanel will crash and restart immediately when clicking on the sound indicator if Music is not installed. Given that neither is listed as a dependency of the other, I can only assume this is a bug.

This behaviour was first observed with Spotify, and reinstalling the bundled music player immediately resolved the issue.

**Comment by davidmhewitt** [comment]
Hi, thanks for the report!

However, I don't seem to be able to reproduce this issue. Are you still able to reproduce this with all of the latest updates installed?

If so, could you try restarting wingpanel in the terminal with the following command and see if there are relevant looking debug lines:
`killall wingpanel && G_MESSAGES_DEBUG=all wingpanel`

**Comment by SweetHangerine** [comment]
I don't seem to be able to reproduce this issue with all packages at current versions, although the issue was consistently reproducible previously.
I'll update you if anything changes, but it appears that the issue is resolved for now.

**Comment by SweetHangerine** [comment]
I've had the issue reappear again, so I expect that this is something that may crop up fairly sporadically. I wanted to provide some more information, however the debug command simply returns:
`Failed to register: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
`

Unfortunately I won't be able to provide anything further until I'm able to resolve this.
