### ISSUE TITLE
General sound indicator not working as expected.

### ISSUE THREAD

**Issue by fernandofreamunde** [elementary/wingpanel-indicator-sound#119]
I have multiple sources of sound and when I lowered the volume in the indicator nothing changed, I had to go to the settings select the output and then change the volume.

previously I had to change the output to the default of the laptop as apparently the system changed the default to be the dock instead of the laptop.

**Comment by tuxiano** [comment]
I have the same issue, but with a different usb device.

Internal device:
`0b:00.3 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-0fh) HD Audio Controller`

Additional USB device:
`0d8c:000c C-Media Electronics, Inc. Audio Adapter`

**Comment by danirabbit** [comment]
We now handle selecting audio devices in the panel, so I think this is probably fixed
