### ISSUE TITLE
All Apps Have The Same Icon.

### ISSUE THREAD

**Issue by Djcoper** [elementary/wingpanel-indicator-sound#127]
![IMG_2019-11-28_03-52-37-01](https://user-images.githubusercontent.com/30577249/69776339-be5f4200-1193-11ea-8def-2bd51fa98e5f.jpeg)

Playing Media : What we currently see left and a mockup of what we should see right.

**Comment by peteruithoven** [comment]
I'm afraid this simply isn't true. 
The apps you're using don't communicate what they are playing in such a way the indicator can pick it up. 

Example using Spotify and Auryo:
![Screenshot from 2019-12-08 17-28-51@2x](https://user-images.githubusercontent.com/523210/70392436-56ed9180-19e0-11ea-8457-53dcca4eec65.png)

Looking at the code the app you're testing with (Chrome?) isn't a MPRIS provider (MediaPlayer2). 
https://github.com/elementary/wingpanel-indicator-sound/blob/master/src/Widgets/MprisGui.vala

Something to try:
https://chrome.google.com/webstore/detail/browser-playerctl/ojjjidifjmbbckdjfiagdfdepbcmnicg

**Comment by peteruithoven** [comment]
From the browser side of things, there now is a API that websites can use to communicate the state of media playing with the underlying operating system. It includes metadata such as artist, album, track name, or album artwork, for example.

https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API
https://developers.google.com/web/updates/2017/02/media-session
Support: https://caniuse.com/#search=Media%20Session%20API
Online demo: https://googlechrome.github.io/samples/media-session/

Currently on Firefox 71 on elementary OS this doesn't work at all. Chrome does work, expect for the artwork sadly.

An issue I've been following for Firefox on Linux: https://bugzilla.mozilla.org/show_bug.cgi?id=1353652

**Comment by peteruithoven** [comment]
This is where we try to extract the artwork:

**Comment by peteruithoven** [comment]
Interestingly these Chrome/Chromium extensions do set this `mpris:artUrl` metadata:
- browser-mpris2: https://github.com/otommod/browser-mpris2/blob/master/native/chrome-mpris2#L345
- browser-playerctl: https://github.com/beingmohit/browser-playerctl/blob/master/mpris2#L345

**Comment by peteruithoven** [comment]
I installed [browser-playerctl](https://github.com/beingmohit/browser-playerctl) and now I am getting more metadata on for example Youtube. (It didn't work with the [Media Session API demo](https://googlechrome.github.io/samples/media-session/audio.html))

Now I get: 
```
xesam:artist => ['Physics Girl'] (as)
xesam:album => '' (s)
xesam:title => 'Only some humans can see this type of light' (s)
mpris:trackid => objectpath '/CSu0cV3fqi8' (o)
mpris:artUrl => 'https://i.ytimg.com/vi/CSu0cV3fqi8/hqdefault.jpg' (s)
mpris:length => int64 585781000 (x)
xesam:url => 'https://www.youtube.com/watch?v=CSu0cV3fqi8' (s)
xesam:title => '(777) Only some humans can see this type of light' (s)
```
And we see the artwork in the indicator:
![Screenshot from 2019-12-14 16-31-22@2x](https://user-images.githubusercontent.com/523210/70850902-94926480-1e8f-11ea-822e-5cad7dc9c63c.png)

Not sure what's up with the "(777)" part. The extension also doesn't correctly communicate the artist (while Chrome itself does).

**Comment by peteruithoven** [comment]
Relevant spec:
https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#mpris:arturl

Relevant Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=951584
Relevant diffs: 
- https://chromium.googlesource.com/chromium/src.git/+/544b1dc0e7a755fe5d8d45944f95ed2601d2d05b%5E!/
- https://chromium.googlesource.com/chromium/src/+/dae5564b63592c361fd3e1de590b7c7bb9ecb0b3%5E!/
Not seeing "artUrl". I've [asked](https://bugs.chromium.org/p/chromium/issues/detail?id=951584#c4) why they didn't include it.

**Comment by peteruithoven** [comment]
I've now also shared this info at:
https://elementaryos.stackexchange.com/questions/21623/cant-control-firefox-media-through-the-sound-indicator-or-keyboard-shortcuts
https://elementaryos.stackexchange.com/questions/21626/no-artwork-shown-for-media-played-through-chromium/21627#21627
