### ISSUE TITLE
Top bar hides on click Volume button

### ISSUE THREAD

**Issue by gabrielgambarra** [elementary/wingpanel-indicator-sound#139]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
I didn't find out what exactly cause it yet but when some softwares are opened and I click on Volume button, the top bar hides for a few seconds and appears again, but the action of open a little dialog for I change Volume doesn't happen.

### To Reproduce
Well, I don't the way to reproduce it. At this moment I'm with Chrome and Android Studio opened.

## Platform Information

![Captura de tela de 2020-03-03 19-13-54](https://user-images.githubusercontent.com/33934389/75828894-4486b800-5d83-11ea-93cf-0a6d0dc0de70.png)

- [X] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by Trendkiller** [comment]
I'm observing the same issue. It replicates every time with Spotify running. So just open Spotify and then click on sound icon. Wingpanel should disappear.

### My spec info:
OS: elementary OS 5.1.2 hera
Kernel: x86_64 Linux 5.3.0-40-generic
Uptime: 11m
Packages: 1686
Shell: bash 4.4.20
Resolution: 1366x768
DE: GNOME 
WM: Mutter(Gala)
WM Theme: elementary
GTK Theme: elementary [GTK2/3]
Icon Theme: elementary
Font: Open Sans 9
CPU: Intel Core i3-3217U @ 4x 1.8GHz
GPU: i915drmfb
RAM: 1071MiB / 3824MiB

**Comment by danrabbit** [comment]
I'm unable to reproduce this issue. Can you provide more details about how you've installed Spotify?

**Comment by Trendkiller** [comment]
> I'm unable to reproduce this issue. Can you provide more details about how you've installed Spotify?

1. Install Spotfiy, as described in the official installation guide: 

> curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
> echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
> sudo apt-get update && sudo apt-get install spotify-client

2. Log-in to Spotify and play a song.
3. While song is playing, click on the "Volume Button".

Actual result: Wingpanel disappears.
Expected result: Wingpanel should work as expected.

**Comment by danrabbit** [comment]
Hm, I can't reproduce this either with the deb from that repo or with the spotify flatpak

Can you try installing the sound indicator from git master and see if that resolves the issue?

**Comment by gabrielgambarra** [comment]
Well, the issue is not valid anymore. This problem was solved on last updates. I'll close the issue. Thanks guys!
