### ISSUE TITLE
Sound indicator crashes the wingpanel

### ISSUE THREAD

**Issue by kepler-dslr** [elementary/wingpanel-indicator-sound#142]
I just installed elementary 5.1 did some updates and now whenever I hover or click on the sound indicator it crash the wingpanel: 

```
** (wingpanel:12525): GLib-GIO-CRITICAL **: 00:16:07.618: g_app_info_get_id: assertion 'G_IS_APP_INFO (appinfo)' failed

** (wingpanel:12525): CRITICAL **: 00:16:07.619: string_replace: assertion 'self != NULL' failed

[1]-  Segmentation fault      wingpanel
```

**Comment by kepler-dslr** [comment]
a little update, seems like removing noise the music app was the fault, so I reinstalled noise and it doesn t crash anymore

**Comment by ryonakano** [comment]
We can close this issue if your issue is fixed :)
