### ISSUE TITLE
Switching default music player doesn't change the behaviour of "music" icon

### ISSUE THREAD

**Issue by kr428** [elementary/wingpanel-indicator-sound#149]
In "preferred apps", I can choose a music player other than elementary music which comes pre-installed (in example byte from the app store). Unfortunately, doing so will still leave the "Music" icon and navigation keys visible / present in the system tray "volume / audio control" menu. This, too, will happen if I decide to completely get rid of and uninstall elementary music. Expected behaviour: Whenever I change the default audio player, this setting should be honoured by the "volume / audio control" menu in the system tray as well.

**Comment by danrabbit** [comment]
Gonna move this to `wingpanel-indicator-sound` since this seems to be an issue with the indicator and not an issue with setting the app as default
