### ISSUE TITLE
Music Appears Two Times in the Audio Shortcut.

### ISSUE THREAD

**Issue by ghost** [elementary/wingpanel-indicator-sound#157]
I have this problem with the Desktop Integration in Elementary OS 5.1.7 Hera, no matter if I open the program from the dock or from the audio shortcut, there's always two of them.

![Captura de pantalla de 2020-08-15 13-40-14](https://user-images.githubusercontent.com/44249820/90320267-3ee6ee00-df2f-11ea-97ac-72c7b566fed6.png)

**Comment by Noryub** [comment]
> I think the first one represents the playing music in your browser and the second one is for Music app itself. I assume this might be the expected behavior.

In the case that no browser is open it still appears, and if I click it, the Music app opens, so it makes me think that the process comes from the Music App, and not the browser.

Anyways, if that would be the case, why not adapt the notification to make it looks like it comes from the browser?

**Comment by Noryub** [comment]
Forget it, it don't comes from any browser, thats for sure.
![20200816 112846](https://user-images.githubusercontent.com/44249820/90340287-a14ef580-dfe6-11ea-94c8-7c5628c77eff.png)

**Comment by rooven** [comment]
Can confirm this issue.
Is not comming from a browser, nor another player, I'm using Hera 5.1.7, installed last week, no other music player open or installed
![Captura de pantalla de 2020-10-02 12-29-40](https://user-images.githubusercontent.com/824288/94960096-dc828680-04b7-11eb-9ce6-0a4bfd4fd0c0.png)

**Comment by ryonakano** [comment]
Many users reports this issue and I can confirm this issue now. Maybe a regression from 54cbfb3?
