### ISSUE TITLE
Ola a um bug no meu elementary os 5.1.7 que faz quando estou ouvindo musica aparecer 2 player debaixo do icone de som purfavor corrija isso estou empaciente

### ISSUE THREAD

**Issue by LuizBeatmaker** [elementary/wingpanel-indicator-sound#158]

**Comment by Chamrosh** [comment]
![Screenshot from 2020-09-29 21 29 39](https://user-images.githubusercontent.com/10561726/94597835-f004d600-029a-11eb-91d2-417e125d169e.png)

**Comment by ryonakano** [comment]
Thank you for your report, but I'm closing this issue as a duplicate of #157.
