### ISSUE TITLE
Move microphone icon to the left

### ISSUE THREAD

**Issue by danrabbit** [elementary/wingpanel-indicator-sound#17]
I'm wondering with the privacy indicator if it makes sense to move the mic to the left of the sound indicator 

![screenshot from 2017-04-23 10 58 18](https://cloud.githubusercontent.com/assets/7277719/25316007/d6c64fd0-2813-11e7-8825-8c48c2de1dea.png)

**Comment by danrabbit** [comment]
@elementary/ux

**Comment by davidmhewitt** [comment]
Or maybe even transition the microphone indicator into the privacy indicator at some point?
