### ISSUE TITLE
Wingpanel Sound Indicator should use a different icon than Switchboard Sound Plug

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/wingpanel-indicator-sound#172]
for reference see https://github.com/elementary/icons/issues/961 and https://github.com/elementary/switchboard-plug-sound/issues/170

**Comment by danrabbit** [comment]
Since this is an AppCenter issue, this is a duplicate of https://github.com/elementary/appcenter/issues/1444
