### ISSUE TITLE
Update to use new smaller switch style

### ISSUE THREAD

**Issue by hanaral** [elementary/wingpanel-indicator-sound#175]
## What Happened

The wingpanel indiator for sound does not use the newer, smaller style that allthe other indicators use.

## Expected Behavior

All the indicators use the same style of switch

## Platform Information

elementary OS 6 Daily

**Comment by cassidyjames** [comment]
I believe this is because the other indicators include the switches in modelbuttons, whereas it's used in a different context here. Not sure what the solution is. @elementary/ux?
