### ISSUE TITLE
Linear output disappears from the list when choosing HDMI/DisplayPort output

### ISSUE THREAD

**Issue by stsdc** [elementary/wingpanel-indicator-sound#189]
I do have 2 monitors and one is capable of playing audio. When I'm choosing it to play audio, the Linear output disappears from a list, so I have to open Settings to choose Linear Output back.

Before choosing HDMI output:
![obraz](https://user-images.githubusercontent.com/6031763/113931935-5bec6c00-97f3-11eb-8954-b8eb0065dd7b.png)

After choosing HDMI output:
![obraz](https://user-images.githubusercontent.com/6031763/113932008-6f97d280-97f3-11eb-874a-8dde276e6103.png)

All available outputs: 
![obraz](https://user-images.githubusercontent.com/6031763/113932114-8a6a4700-97f3-11eb-9c96-36501f56fa3c.png)

*Only S/PDIF is not connected.

**Comment by bluesabre** [comment]
Maybe the best way to handle the priority / displayed devices is to remember any that have been previously selected and keep them in the list. I can work on a patch for this.
