### ISSUE TITLE
Long device names should be trimmed 

### ISSUE THREAD

**Issue by JoseExposito** [elementary/wingpanel-indicator-sound#190]
## What Happened

My sound devices have a long name, making the indicator too wide.

![audio](https://user-images.githubusercontent.com/1335948/114058888-23e93580-9894-11eb-8d8f-a2a1c1c519b4.png)

## Expected Behavior

I'd like the names to be trimmed

![sound-trimmed](https://user-images.githubusercontent.com/1335948/114058924-2b104380-9894-11eb-8d4e-a7b3fc390580.png)

## Platform Information

elementary OS 6

**Comment by danrabbit** [comment]
I think probably middle ellipsis is better here to make sure you can distinguish between devices with similar names
