### ISSUE TITLE
Not showing Spotify album art

### ISSUE THREAD

**Issue by kdwk** [elementary/wingpanel-indicator-sound#218]
## What Happened

wingpanel-indicator-sound is not showing Spotify album art:
![Screenshot from 2021-08-23 09-12-27](https://user-images.githubusercontent.com/39268094/130377288-a84984b7-fb99-4886-9fe7-737cdb6ed221.png)

Even though wingpanel-indicator-notifications successfully gets the artwork:
![Screenshot from 2021-08-23 09-12-23](https://user-images.githubusercontent.com/39268094/130377319-0d4c80fd-ea1c-4e89-88ed-d38c65f5a0ff.png)

## Expected Behavior

wingpanel-indicator-sound should display Spotify album art correctly, as wingpanel-indicator-notifications seems to successfully receive the artwork

## Steps to Reproduce

1. Open Spotify
2. Play something
3. Open wingpanel-indicator-sound and see how the artwork is not displayed

**Comment by danrabbit** [comment]
This is a known bug in Spotify. I'm sorry to say you'll have to wait for them to fix it. We don't have the ability to fix bugs in third party apps

**Comment by kdwk** [comment]
For the record, this bug is now fixed. Spotify reports album art as of Flatpak com.spotify.Client 1.1.68.632.g2b11de83
