### ISSUE TITLE
fails to compile with vala ≥ 0.53.1

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-sound#219]
Both the latest stable release and git master fail to compile on Fedora 35 / Rawhide since vala was updated to version 0.53.1 with this error message:

```
../src/Services/MediaPlayer.vala:33.5-33.32: error: Name `_type' is not valid for a GLib.Object property
    public abstract string _type { owned get; }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Not sure if this has always been a problem and vala only now starts to report this an error, or if this is a "new" problem with vala ≥ 0.53.1.

**Comment by bobby285271** [comment]
Seems that simply removing the line (`public abstract string _type { owned get; }`) can make things ***compiles*** with 0.54 (did not test using it yet).

I think this is the reason: https://gitlab.gnome.org/GNOME/vala/-/commit/38d61fbff037687ea4772e6df85c7e22a74b335e
