### ISSUE TITLE
External speaker doesn’t play sound on Odin

### ISSUE THREAD

**Issue by diogopessoa** [elementary/wingpanel-indicator-sound#220]
## What Happened

When I connect the external speakers to the notebook, there is no sound.

## Expected Behavior

Play sound on the speakers after connected to the notebook.

## Steps to Reproduce

1. Connect the external speaker to the notebook;
2. when I play the music, there is no sound from the external speakers. 

https://user-images.githubusercontent.com/12633864/131549248-a9d29687-cc93-47c8-8454-c41af621ccf4.mp4

### Logs

I used two different brand speakers.
In Hera version it worked. I also have openSUSE on the same notebook and the external speaker works fine.

## Platform Information

![Captura de tela de 2021-08-31 06 19 11](https://user-images.githubusercontent.com/12633864/131550854-372163cf-aa18-494e-9662-67501fd07e81.png)
![Captura de tela de 2021-08-31 06 19 32](https://user-images.githubusercontent.com/12633864/131550858-dc1415f1-73c1-435c-8e19-c8065a0b591c.png)
notebook Asus K46ca
wired speaker C3 Tech

**Comment by cassidyjames** [comment]
@diogopessoa what's selected as the output in System Settings → Sound?

**Comment by diogopessoa** [comment]
> @diogopessoa what's selected as the output in System Settings → Sound?

I already tried both options: speaker and headphones.

![Screenshot from 2021-08-31 17-39-22](https://user-images.githubusercontent.com/12633864/131573542-b27fa649-3dfe-4999-b1c8-babdc7a9aa7d.png)

My headphones are muted too.

**Comment by diogopessoa** [comment]
Solved! 

I simply executed the command on the terminal: **alsactl restore**

after that the sound worked on the headphones and external speaker! 🤗
