### ISSUE TITLE
Changing the volume step when using scroll

### ISSUE THREAD

**Issue by Obema12** [elementary/wingpanel-indicator-sound#233]
I changed the default volume step by setting `volume-step 5`. Now keyboard shortcuts change the volume by the 5% I specified, and using scrolling - by 6%. Can this be fixed?

**Comment by jeremypw** [comment]
Looking at the code the volume step used on scrolling is hard coded. This needs to be obtained from the setting `org.gnome.settings-daemon.plugins.media-keys.volume-step` I guess.
