### ISSUE TITLE
wingpanel size claim to wide.

### ISSUE THREAD

**Issue by kvdz** [elementary/wingpanel-indicator-sound#24]
![screenshot from 2017-06-08 21-49-35](https://user-images.githubusercontent.com/4341214/26947839-67db5c96-4c94-11e7-89de-6016dec70b62.png)

There is no microphone (there shouldn' t be one in my case)  but the space is to wide that is claims.

**Comment by danrabbit** [comment]
This is a bug in Gtk+ due to animations being disabled. `Gtk.Revealer` will reserve the full amount of space instead of the correct amount
