### ISSUE TITLE
Wingpanel closes when one tries to click on wingpanel sound indicator

### ISSUE THREAD

**Issue by diegomagela** [elementary/wingpanel-indicator-sound#253]
### What Happened?

Wingpanel closes (crash - segment fault) when one tries to click on wingpanel sound indicator when a sound is playing by any browser when the native apps Music and Videos are uninstalled.

### Steps to Reproduce

1. Uninstall Music
2. Uninstall Videos
3. Kill wingpanel (io.elementary.wingpanel)
4. Open wingapnel (io.elementary.wingpanel)
5. Open any browser and play a video from YouTube, for example (https://www.youtube.com/watch?v=Xnmzins2Uow&ab_channel=FooFighters)
6. Try to click on the sound indicator

### Expected Behavior

Show up the sound indicator menu.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
(io.elementary.wingpanel:12336): io.elementary.wingpanel.sound-CRITICAL **: 11:34:31.347: string_replace: assertion 'self != NULL' failed
Segmentation fault
```

### Hardware Info

Quad-Core 11th Gen Intel® Core(TM) i7-11390H @ 3.40GHz
Intel® TigerLake-LP GT2 [Iris Xe Graphics]
NVIDIA Corporation TU117M [GeForce MX450] (NVIDIA drivers are not installed).

**Comment by tintou** [comment]
Hi there, we need more information on why this crash is happening to you, would you mind following the instructions at https://docs.elementary.io/contributor-guide/feedback/reporting-issues/inspecting-crashes#investigating-spontaneous-crashes and pasting the output of `coredumpctl debug io.elementary.wingpanel`
Thank you!

**Comment by diegomagela** [comment]
My computer freezes when I tried to do that. It did not reboot anymore. I cannot take a screenshot. I had to reinstall the OS. When I redo the steps to reproduce the problem, it happened again.
