### ISSUE TITLE
Toggle play-pause on right-click

### ISSUE THREAD

**Issue by teamcons** [elementary/wingpanel-indicator-sound#283]
### Problem

You can change volume or toggle mute on the indicator. However there is no on-the-fly way to pause or continue something - one must open the indicator and snipe the right button

It would be nifty to toggle quickly because you were listening to some cool music but someone rung the door and you have to check who that is

### Proposal

Whenever an app playing sound gets paused:
save what app that is in a Last_Paused variable

Handle Right-click on indicator :
-If something is playing --> Pause it (saving what in the process)
-If nothing is playing --> Is the app saved in Last_Paused still here ? Unpause it.

**Comment by danirabbit** [comment]
I think this would go against expectations for what right click means across the system. I can't think of any other time where a right click directly triggers an action rather than spawning a context menu

**Comment by teamcons** [comment]
Maybe then an argument could be made to replace mute/unmute on middle ?
While "mute" seem appropriate since the indicator represent sound, im not sure how often the need to mute/unmute everything arise VS the need to pause/unpause whatever makes sound
