### ISSUE TITLE
Wide range on volume indicator with disabled animation

### ISSUE THREAD

**Issue by varlesh** [elementary/wingpanel-indicator-sound#30]
If disable animation on wingpanel > volume indicator have wide range.
`gsettings set org.gnome.desktop.interface enable-animations false`
![2017-08-23 06 57 33](https://user-images.githubusercontent.com/8083855/29599621-5f070070-87d1-11e7-85b1-790e98f818a2.png)

**Comment by varlesh** [comment]
See mouse click position ():
![2017-08-23 07 12 49](https://user-images.githubusercontent.com/8083855/29599825-8e7da81c-87d2-11e7-85ec-f585b6b3bdfc.png)

**Comment by varlesh** [comment]
If remove package `wingpanel-indicator-sound` all fine:
![2017-08-23 07 18 06](https://user-images.githubusercontent.com/8083855/29599970-543d4fda-87d3-11e7-81fd-8215b5de3e4b.png)

**Comment by parnold-x** [comment]
Duplicate of https://github.com/elementary/wingpanel-indicator-sound/issues/24
