### ISSUE TITLE
Microphone "Tattler" doesn't detect OBS reliably

### ISSUE THREAD

**Issue by danirabbit** [elementary/wingpanel-indicator-sound#34]
I have OBS studio open and I'm streaming and there is no indicator in the panel

**Comment by Philip-Scott** [comment]
Does OBS use pulse-audio? Or do you run the app with Sudo? It might be grabbing your mic at a lower level than PulseAudio can detect

Check the Audio panel in Switchboard

**Comment by lenemter** [comment]
@danirabbit Can you reproduce this issue?

**Comment by danirabbit** [comment]
I can't reproduce this anymore :)
