### ISSUE TITLE
No Music application recognized by meda contols

### ISSUE THREAD

**Issue by arshubham** [elementary/wingpanel-indicator-sound#38]
I have music player (https://github.com/artemanufrij/playmymusic)  as my default music player. 
On installing and opening spotify from flatpak (not logged in yet). I noted this in the indicator
![screenshot from 2017-11-16 14-35-20](https://user-images.githubusercontent.com/14235191/32890512-1ef97460-caf5-11e7-9d46-52aa6db84948.png)

**Comment by danirabbit** [comment]
Closing since this is very old and a lot has changed since 6 years ago
