### ISSUE TITLE
Audio feedback when adjusting volume is redundant

### ISSUE THREAD

**Issue by nkkollaw** [elementary/wingpanel-indicator-sound#40]
It's very cute, but I think having audio feedback when you adjust the volume is redundant.

Main reasons are:

- one never adjusts the volume for fun, just when there's already sound coming out and you don't like the volume level, so you can gauge by the actual sound or movie you're playing
- one never adjusts the volume for fun, just when there's already sound coming out and you don't like the volume level, so the visual feedback covers whatever you're already playing and screws up the experience
- the sound effect can give me an idea about the volume level that that specific sound is confortable to me at, but it's no indication that the volume level will be OK for YouTube, Spotify, etc. since most things have different volume levels

**Comment by chrisdotcode** [comment]
> one never adjusts the volume for fun, just when there's already sound coming out and you don't like the volume level, so you can gauge by the actual sound or movie you're playing

I personally preemptively adjust sound settings all the time: (when plugging in a new headset, when removing one, etc.); I don't think I'm the only one, either.

**Comment by nkkollaw** [comment]
Don't worry @chrisdotcode, no one even bothered looking at this.

**Comment by danrabbit** [comment]
Going to close this as "Won't fix" for the reasons that chrisdotcode states
