### ISSUE TITLE
Select volume level icon to toggle mute/unmute

### ISSUE THREAD

**Issue by nkkollaw** [elementary/wingpanel-indicator-sound#41]
I thought that to mute audio I could just click on the speaker on the left, since it's often (always?) how it works.

Instead, there's a switch control.

I don't think it's necessary, since everyone is used to clicking on the speaker to mute.

Having the switch therefore:
- makes the experience worse, because the intuitive thing to do is to click on the speaker icon
- adds an unnecessary element, while elementary OS strives for simplicity and remove elements that are not needed

**Comment by Thalexander** [comment]
Matching the behaviour of other platforms is not necessarily intuitive, throughout elementary toggle switches are used and would be recognised by users, they also give visual indication that it can be toggled, whereas just the speaker would require them to be familiar with that behaviour which is also not present elsewhere on elementary.

**Comment by nkkollaw** [comment]
Not necessarily, but in this case it is. Other platforms are  what the users are coming from and are familiar with. The "save" icon is often a floppy disk because people recognize it, but not many of us have used one.

If you really want to go for the toggle, should it be on the left, not on the right, as it is in most interfaces like web forms?

**Comment by danrabbit** [comment]
I disagree that the toggle switch should be removed, but I think adding a toggle behavior to the volume level icon seems like a sane feature request. Re-titling to that effect.

In the future please try to describe only one change per issue report. It makes things easier to track :)
