### ISSUE TITLE
Integrate with HTML5 <audio>/<video>?

### ISSUE THREAD

**Issue by chrisdotcode** [elementary/wingpanel-indicator-sound#42]
If there's someway that the notification panel/pulseaudio can pick up `<audio>`/`<video>` tags in browsers, we can integrate what is currently playing in the notification dock and be able to play/pause/forward it straight from the notification dock/your play/pause buttons on your laptop/your headset.

- - -
While I'm here, do bluetooth play/pause/next controls even work from headsets? I have a pair of Beats, and I haven't been able to get them to play nice with Music.

**Comment by chrisdotcode** [comment]
@danrabbit Is something like this feasible?

**Comment by tintou** [comment]
There is nothing we can do here, you should fill the bug at Webkit-gtk itself (or any browser), what they have to do is to integrate with the MPRIS interface.
Bluetooth headsets using standard protocols should work with Music.
