### ISSUE TITLE
Color of icon (muted volume) changes when power cord is plugged in/out of laptop

### ISSUE THREAD

**Issue by ianrabt** [elementary/wingpanel-indicator-sound#64]
This is on the first Juno beta, on a hidpi screen (200% scaling).

### Here is the status bar with power unplugged:

![image](https://user-images.githubusercontent.com/5727598/42602016-b2974a30-8535-11e8-9e3a-87b5232a231e.png)

### And after plugging in the power cord:

![image](https://user-images.githubusercontent.com/5727598/42602045-d6ee2f3e-8535-11e8-9251-37431a391af5.png)

### After waiting about ten seconds, the icon returns to its normal color:

![image](https://user-images.githubusercontent.com/5727598/42602065-e6f4cbb8-8535-11e8-9f2b-e02716e5bf7a.png)

**Comment by btkostner** [comment]
This is intended. When it has color it means some audio is being played (but muted.)

**Comment by ianrabt** [comment]
Ah I see, that makes sense -- and is very useful functionality now that I understand what the color means :)
