### ISSUE TITLE
Disable horizontal scroll on the sound indicator icon

### ISSUE THREAD

**Issue by Blast-City** [elementary/wingpanel-indicator-sound#71]
Hi.

Problem 1:

1 - Move the cursor to the sound indicator.

2- Use the horizontal scroll.

Result: Horizontal scrolling doesn't do anything but the volume changing sound is played in a longer way.

Problem 2:

1 - move the cursor to the sound indicator.

2 - Left click on the sound indicator.

3 - Try to scroll horizontally.

Result: Horizontal scrolling doesn't do anything, but the volume changing sound is played with a weird pitch.

**Comment by jeremypw** [comment]
@Astro-City :  In Problem 2, where are you pointing?  You have opened the popup, but are you still pointing at the icon, or have you moved to the scale (or somewhere else)?

**Comment by Astro-City** [comment]
> @Astro-City : In Problem 2, where are you pointing? You have opened the popup, but are you still pointing at the icon, or have you moved to the scale (or somewhere else)?

Hi.

On "Problem 2" i didn't moved the cursor after pressing the volume icon. 

If you move the cursor to the slider after pressing the button (pop up open), you get a similar behavior as "Problem 1" when you use the horizontal scroll.

I was not able to reproduce the problem in any other location.

Thanks.

Note: This was tested on Loki and Juno (Live USB).

**Comment by jeremypw** [comment]
@Blast-City :  Sorry for getting your name wrong and thanks for the info!   It has been suggested that horizontal scrolling makes sense on a horizontal scale so I have limited this report to horizontal scrolling on the icon.  If there is an issue with the scale that should be raised separately (it is dealt with by separate code).

**Comment by Blast-City** [comment]
> @Blast-City : Sorry for getting your name wrong and thanks for the info! It has been suggested that horizontal scrolling makes sense on a horizontal scale so I have limited this report to horizontal scrolling on the icon. If there is an issue with the scale that should be raised separately (it is dealt with by separate code).

Hi.

I changed my name. Sorry for confusing you.
