### ISSUE TITLE
Volume button in the keyboard is not working

### ISSUE THREAD

**Issue by flowershe** [elementary/wingpanel-indicator-sound#77]

**Comment by peteruithoven** [comment]
I think we're going to need a little bit more information...
It has never worked? 
What kind of keyboard and keyboard configuration do you have? 
What version of elementary OS are you running?

**Comment by raibtoffoletto** [comment]
I can back this up.
My control from keyboard doesn't work after I come back from sleep. 
From a clean boot, there is no problem, the indicator works fine, from a sleep it stop 
responding to the acpi events. The acpid action button/volumedown is recognised by the system
but the applet stop reacting to them....

For the moment I've been using a simple acpid script (github.com/raibtoffoletto/pulseaudio-acpid-fix)
for a quick fix, but I don't know exactly how to debug the indicator!

Elementary Juno 5.0 (up-to-date)
Keyboard: DasKeyboard 4 Root (no rgb)

**Comment by peteruithoven** [comment]
@raibtoffoletto thanks for the information. 

> The acpid action button/volumedown is recognised by the system but the applet stop reacting to them....

How can you tell it's recognized by the system?
With applet you mean the sound indicator? You for example don't see the indicator icon volume and the volume slider adapt to the volume?

Could you try to restart the `gsd-media-keys` process (run `killall gsd-media-keys`) to see if that temporarily fixes the issue for you? Possibly relevant: https://github.com/elementary/gala/issues/193

( Just to be clear, the indicator has nothing to do with how you can control audio using the keyboard. )

**Comment by raibtoffoletto** [comment]
Dear Peter,
when using `acpi_listen` I can see that key strokes are being registered. 

>[toffoletto@elemental ~]$ acpi_listen 
>button/volumeup VOLUP 00000080 00000000 K
>button/volumedown VOLDN 00000080 00000000 K

however the sound-indicator (sound applet, or how it should be called) wont react, and wont change
the volume anymore.

`gsd-media-keys` seems not to be installed, or not a available command. 
also `ps -A` returns no gsd in my system...

I don't know how the indicator should work, for example, it's fine when I boot, I can manage to change the volume and it will show me the notification that's doing so, after a sleep it doesn't do that and the volume is not changed. With my little acpid scripts I can still control the pulseaudio volume after a sleep, but the indicator won't show me the notifications, it will only react passively to the audio changes.
(I'm not sure I'm clear in trying to writing this behaviour).

PS: Related to the gala#193, I've noticed before that the terminal Win+T stopped to work sometimes, however I just assign a custom shortcut (Win+T to the command to open the terminal) and it won't fail anymore... probably those are related.

**Comment by peteruithoven** [comment]
If you use htop and filter on gsd there should be a whole list, among them `gsd-media-keys`. If I run: `ps -A | grep gsd` I get: 
```
14355 ?        00:00:00 gsd-rfkill
14358 ?        00:00:00 gsd-power
14363 ?        00:00:00 gsd-clipboard
14364 ?        00:00:03 gsd-color
14365 ?        00:00:00 gsd-datetime
14369 ?        00:00:00 gsd-wacom
14371 ?        00:00:00 gsd-print-notif
14375 ?        00:00:00 gsd-keyboard
14378 ?        00:00:01 gsd-sharing
14388 ?        00:00:00 gsd-sound
14406 ?        00:00:01 gsd-housekeepin
14414 ?        00:00:00 gsd-mouse
14419 ?        00:00:00 gsd-xsettings
14427 ?        00:00:00 gsd-a11y-settin
14430 ?        00:00:00 gsd-smartcard
14500 ?        00:00:00 gsd-printer
32682 ?        00:00:00 gsd-media-keys
```

> it will only react passively to the audio changes.
How though? 

The volume change notifications are shown by Gala's notify plugin btw.

**Comment by danirabbit** [comment]
Gonna close this since it seems like OP had an issue with GSD media keys and not with the sound indicator and this is now quite old
