### ISSUE TITLE
Middle-clicking the mic icon should mute input, not output

### ISSUE THREAD

**Issue by cassidyjames** [elementary/wingpanel-indicator-sound#78]
Right now, middle-clicking anywhere on the indicator in the panel mutes the output. However, it would be handy (and expected) if middle-clicking the microphone would mute input instead.

**Comment by codygarver** [comment]
I use this feature, I don't know about this one. I would be surprised if middle clicking the volume icon didn't affect the volume. This is also optimizing for situations involving a mic, which is more rare than situations involving output volume.
